### ISSUE TITLE
Index is undefined in Bundle:suspend

### ISSUE THREAD

**Issue by camchenry** [bakpakin/corope#1]
Whenever I do a call to rope:listen, the thread crashes because the table index is nil. Specifically, it errors on the line  `ts[index] = ts[#ts]` on [line 73](https://github.com/bakpakin/corope/blob/master/corope.lua#L73). I can't find `index` defined anywhere, so I'm not sure what was meant here.

Example of the code I'm using:

```lua

bundle(function(rope)
    -- do something
    rope:listen("keypress") -- crashes here
    -- do more stuff
end)
```

**Comment by bakpakin** [comment]
It seems that I was a line code. index should be defined as rope.index. I just pushed a very quick fix.

**Comment by camchenry** [comment]
Thanks for the quick fix! I figured it out just as you pushed the update.
